// <auto-generated />
using System;
using InvestmentCalculator.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvestmentCalculator.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("InvestmentCalculator.Models.Calculation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CalculationDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("FutureValue")
                        .HasColumnType("REAL");

                    b.Property<double>("InitialAmount")
                        .HasColumnType("REAL");

                    b.Property<double>("InterestRate")
                        .HasColumnType("REAL");

                    b.Property<double>("MonthlyContribution")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalInterest")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalInvested")
                        .HasColumnType("REAL");

                    b.Property<int>("Years")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Calculations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
